//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ChangeState_Response_.h
//  Source: lifecycle_msgs\srv\dds_opensplice\ChangeState_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _CHANGESTATE_RESPONSE__H_
#define _CHANGESTATE_RESPONSE__H_

#include "sacpp_mapping.h"
#include "lifecycle_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace lifecycle_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct ChangeState_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs ChangeState_Response_
         {
               DDS::Boolean success_;
         };

         typedef DDS_DCPSStruct_var < ChangeState_Response_> ChangeState_Response__var;
         typedef ChangeState_Response_&ChangeState_Response__out;
      }
   }
}




#endif
