//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetAvailableTransitions_Response_.h
//  Source: lifecycle_msgs\srv\dds_opensplice\GetAvailableTransitions_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETAVAILABLETRANSITIONS_RESPONSE__H_
#define _GETAVAILABLETRANSITIONS_RESPONSE__H_

#include "sacpp_mapping.h"
#include "TransitionDescription_.h"
#include "lifecycle_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace lifecycle_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct GetAvailableTransitions_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Response_
         {
               struct _available_transitions__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < ::lifecycle_msgs::msg::dds_::TransitionDescription_, struct _available_transitions__seq_uniq_> _available_transitions__seq;
               typedef DDS_DCPSSequence_var < _available_transitions__seq> _available_transitions__seq_var;
               typedef DDS_DCPSSequence_out < _available_transitions__seq> _available_transitions__seq_out;
               _available_transitions__seq available_transitions_;
         };

         typedef DDS_DCPSStruct_var < GetAvailableTransitions_Response_> GetAvailableTransitions_Response__var;
         typedef DDS_DCPSStruct_out < GetAvailableTransitions_Response_> GetAvailableTransitions_Response__out;
      }
   }
}




#endif
