#ifndef GETAVAILABLETRANSITIONS_RESPONSE_DCPS_IDL_
#define GETAVAILABLETRANSITIONS_RESPONSE_DCPS_IDL_

#include "dds_dcps.idl"

#include "GetAvailableTransitions_Response_.idl"

module lifecycle_msgs {

    module srv {

        module dds_ {

            typedef sequence<GetAvailableTransitions_Response_> GetAvailableTransitions_Response_Seq;

            local interface GetAvailableTransitions_Response_TypeSupportInterface : ::DDS::TypeSupport { };

            local interface GetAvailableTransitions_Response_DataWriter : ::DDS::DataWriter {
                ::DDS::InstanceHandle_t register_instance(
                  in GetAvailableTransitions_Response_ instance_data);

                ::DDS::InstanceHandle_t register_instance_w_timestamp(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::Time_t source_timestamp);

                ::DDS::ReturnCode_t unregister_instance(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::InstanceHandle_t handle);

                ::DDS::ReturnCode_t unregister_instance_w_timestamp(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::InstanceHandle_t handle,
                  in ::DDS::Time_t source_timestamp);

                ::DDS::ReturnCode_t write(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::InstanceHandle_t handle);

                ::DDS::ReturnCode_t write_w_timestamp(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::InstanceHandle_t handle,
                  in ::DDS::Time_t source_timestamp);

                ::DDS::ReturnCode_t dispose(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::InstanceHandle_t handle);

                ::DDS::ReturnCode_t dispose_w_timestamp(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::InstanceHandle_t handle,
                  in ::DDS::Time_t source_timestamp);

                ::DDS::ReturnCode_t writedispose(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::InstanceHandle_t handle);

                ::DDS::ReturnCode_t writedispose_w_timestamp(
                  in GetAvailableTransitions_Response_ instance_data,
                  in ::DDS::InstanceHandle_t handle,
                  in ::DDS::Time_t source_timestamp);

                ::DDS::ReturnCode_t get_key_value(
                  inout GetAvailableTransitions_Response_ key_holder,
                  in ::DDS::InstanceHandle_t handle);

                ::DDS::InstanceHandle_t lookup_instance(
                  in GetAvailableTransitions_Response_ instance_data);

            };

            local interface GetAvailableTransitions_Response_DataReader : ::DDS::DataReader {
                ::DDS::ReturnCode_t read(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t take(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t read_w_condition(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::ReadCondition a_condition);

                ::DDS::ReturnCode_t take_w_condition(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::ReadCondition a_condition);

                ::DDS::ReturnCode_t read_next_sample(
                  inout GetAvailableTransitions_Response_ received_data,
                  inout ::DDS::SampleInfo sample_info);

                ::DDS::ReturnCode_t take_next_sample(
                  inout GetAvailableTransitions_Response_ received_data,
                  inout ::DDS::SampleInfo sample_info);

                ::DDS::ReturnCode_t read_instance(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t take_instance(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t read_next_instance(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t take_next_instance(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t read_next_instance_w_condition(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::ReadCondition a_condition);

                ::DDS::ReturnCode_t take_next_instance_w_condition(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::ReadCondition a_condition);

                ::DDS::ReturnCode_t return_loan(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq);

                ::DDS::ReturnCode_t get_key_value(
                  inout GetAvailableTransitions_Response_ key_holder,
                  in ::DDS::InstanceHandle_t handle);

                ::DDS::InstanceHandle_t lookup_instance(
                  in GetAvailableTransitions_Response_ instance);

            };

            local interface GetAvailableTransitions_Response_DataReaderView : ::DDS::DataReaderView {
                ::DDS::ReturnCode_t read(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t take(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t read_w_condition(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::ReadCondition a_condition);

                ::DDS::ReturnCode_t take_w_condition(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::ReadCondition a_condition);

                ::DDS::ReturnCode_t read_next_sample(
                  inout GetAvailableTransitions_Response_ received_data,
                  inout ::DDS::SampleInfo sample_info);

                ::DDS::ReturnCode_t take_next_sample(
                  inout GetAvailableTransitions_Response_ received_data,
                  inout ::DDS::SampleInfo sample_info);

                ::DDS::ReturnCode_t read_instance(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t take_instance(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t read_next_instance(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t take_next_instance(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::SampleStateMask sample_states,
                  in ::DDS::ViewStateMask view_states,
                  in ::DDS::InstanceStateMask instance_states);

                ::DDS::ReturnCode_t read_next_instance_w_condition(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::ReadCondition a_condition);

                ::DDS::ReturnCode_t take_next_instance_w_condition(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq,
                  in long max_samples,
                  in ::DDS::InstanceHandle_t a_handle,
                  in ::DDS::ReadCondition a_condition);

                ::DDS::ReturnCode_t return_loan(
                  inout GetAvailableTransitions_Response_Seq received_data,
                  inout ::DDS::SampleInfoSeq info_seq);

                ::DDS::ReturnCode_t get_key_value(
                  inout GetAvailableTransitions_Response_ key_holder,
                  in ::DDS::InstanceHandle_t handle);

                ::DDS::InstanceHandle_t lookup_instance(
                  in GetAvailableTransitions_Response_ instance);
            };
        };

    };

};

#endif
