//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetAvailableTransitions_Request_Dcps.h
//  Source: lifecycle_msgs\srv\dds_opensplice\GetAvailableTransitions_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETAVAILABLETRANSITIONS_REQUEST_DCPS_H_
#define _GETAVAILABLETRANSITIONS_REQUEST_DCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "GetAvailableTransitions_Request_.h"
#include "lifecycle_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace lifecycle_msgs
{
   namespace srv
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Request_TypeSupportInterface;

         typedef GetAvailableTransitions_Request_TypeSupportInterface * GetAvailableTransitions_Request_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < GetAvailableTransitions_Request_TypeSupportInterface> GetAvailableTransitions_Request_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < GetAvailableTransitions_Request_TypeSupportInterface> GetAvailableTransitions_Request_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Request_DataWriter;

         typedef GetAvailableTransitions_Request_DataWriter * GetAvailableTransitions_Request_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < GetAvailableTransitions_Request_DataWriter> GetAvailableTransitions_Request_DataWriter_var;
         typedef DDS_DCPSInterface_out < GetAvailableTransitions_Request_DataWriter> GetAvailableTransitions_Request_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Request_DataReader;

         typedef GetAvailableTransitions_Request_DataReader * GetAvailableTransitions_Request_DataReader_ptr;
         typedef DDS_DCPSInterface_var < GetAvailableTransitions_Request_DataReader> GetAvailableTransitions_Request_DataReader_var;
         typedef DDS_DCPSInterface_out < GetAvailableTransitions_Request_DataReader> GetAvailableTransitions_Request_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Request_DataReaderView;

         typedef GetAvailableTransitions_Request_DataReaderView * GetAvailableTransitions_Request_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < GetAvailableTransitions_Request_DataReaderView> GetAvailableTransitions_Request_DataReaderView_var;
         typedef DDS_DCPSInterface_out < GetAvailableTransitions_Request_DataReaderView> GetAvailableTransitions_Request_DataReaderView_out;

         struct GetAvailableTransitions_Request_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < GetAvailableTransitions_Request_, struct GetAvailableTransitions_Request_Seq_uniq_> GetAvailableTransitions_Request_Seq;
         typedef DDS_DCPSSequence_var < GetAvailableTransitions_Request_Seq> GetAvailableTransitions_Request_Seq_var;
         typedef DDS_DCPSSequence_out < GetAvailableTransitions_Request_Seq> GetAvailableTransitions_Request_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Request_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef GetAvailableTransitions_Request_TypeSupportInterface_ptr _ptr_type;
            typedef GetAvailableTransitions_Request_TypeSupportInterface_var _var_type;

            static GetAvailableTransitions_Request_TypeSupportInterface_ptr _duplicate (GetAvailableTransitions_Request_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetAvailableTransitions_Request_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static GetAvailableTransitions_Request_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetAvailableTransitions_Request_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            GetAvailableTransitions_Request_TypeSupportInterface_ptr _this () { return this; }


         protected:
            GetAvailableTransitions_Request_TypeSupportInterface () {};
            ~GetAvailableTransitions_Request_TypeSupportInterface () {};
         private:
            GetAvailableTransitions_Request_TypeSupportInterface (const GetAvailableTransitions_Request_TypeSupportInterface &);
            GetAvailableTransitions_Request_TypeSupportInterface & operator = (const GetAvailableTransitions_Request_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Request_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef GetAvailableTransitions_Request_DataWriter_ptr _ptr_type;
            typedef GetAvailableTransitions_Request_DataWriter_var _var_type;

            static GetAvailableTransitions_Request_DataWriter_ptr _duplicate (GetAvailableTransitions_Request_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetAvailableTransitions_Request_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static GetAvailableTransitions_Request_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetAvailableTransitions_Request_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            GetAvailableTransitions_Request_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const GetAvailableTransitions_Request_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const GetAvailableTransitions_Request_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const GetAvailableTransitions_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const GetAvailableTransitions_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const GetAvailableTransitions_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const GetAvailableTransitions_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const GetAvailableTransitions_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const GetAvailableTransitions_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const GetAvailableTransitions_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const GetAvailableTransitions_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (GetAvailableTransitions_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetAvailableTransitions_Request_& instance_data) = 0;

         protected:
            GetAvailableTransitions_Request_DataWriter () {};
            ~GetAvailableTransitions_Request_DataWriter () {};
         private:
            GetAvailableTransitions_Request_DataWriter (const GetAvailableTransitions_Request_DataWriter &);
            GetAvailableTransitions_Request_DataWriter & operator = (const GetAvailableTransitions_Request_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Request_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef GetAvailableTransitions_Request_DataReader_ptr _ptr_type;
            typedef GetAvailableTransitions_Request_DataReader_var _var_type;

            static GetAvailableTransitions_Request_DataReader_ptr _duplicate (GetAvailableTransitions_Request_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetAvailableTransitions_Request_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static GetAvailableTransitions_Request_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetAvailableTransitions_Request_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            GetAvailableTransitions_Request_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (GetAvailableTransitions_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (GetAvailableTransitions_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (GetAvailableTransitions_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetAvailableTransitions_Request_& instance) = 0;

         protected:
            GetAvailableTransitions_Request_DataReader () {};
            ~GetAvailableTransitions_Request_DataReader () {};
         private:
            GetAvailableTransitions_Request_DataReader (const GetAvailableTransitions_Request_DataReader &);
            GetAvailableTransitions_Request_DataReader & operator = (const GetAvailableTransitions_Request_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetAvailableTransitions_Request_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef GetAvailableTransitions_Request_DataReaderView_ptr _ptr_type;
            typedef GetAvailableTransitions_Request_DataReaderView_var _var_type;

            static GetAvailableTransitions_Request_DataReaderView_ptr _duplicate (GetAvailableTransitions_Request_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetAvailableTransitions_Request_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static GetAvailableTransitions_Request_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetAvailableTransitions_Request_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            GetAvailableTransitions_Request_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (GetAvailableTransitions_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (GetAvailableTransitions_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (GetAvailableTransitions_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (GetAvailableTransitions_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetAvailableTransitions_Request_& instance) = 0;

         protected:
            GetAvailableTransitions_Request_DataReaderView () {};
            ~GetAvailableTransitions_Request_DataReaderView () {};
         private:
            GetAvailableTransitions_Request_DataReaderView (const GetAvailableTransitions_Request_DataReaderView &);
            GetAvailableTransitions_Request_DataReaderView & operator = (const GetAvailableTransitions_Request_DataReaderView &);
         };

      }
   }
}




#endif
