//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetState_Response_.h
//  Source: lifecycle_msgs\srv\dds_opensplice\GetState_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETSTATE_RESPONSE__H_
#define _GETSTATE_RESPONSE__H_

#include "sacpp_mapping.h"
#include "State_.h"
#include "lifecycle_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace lifecycle_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct GetState_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs GetState_Response_
         {
               ::lifecycle_msgs::msg::dds_::State_ current_state_;
         };

         typedef DDS_DCPSStruct_var < GetState_Response_> GetState_Response__var;
         typedef DDS_DCPSStruct_out < GetState_Response_> GetState_Response__out;
      }
   }
}




#endif
