//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_ChangeState_Response_.h
//  Source: lifecycle_msgs\srv\dds_opensplice\Sample_ChangeState_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SAMPLE_CHANGESTATE_RESPONSE__H_
#define _SAMPLE_CHANGESTATE_RESPONSE__H_

#include "sacpp_mapping.h"
#include "ChangeState_Response_.h"
#include "lifecycle_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace lifecycle_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct Sample_ChangeState_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs Sample_ChangeState_Response_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               ChangeState_Response_ response_;
         };

         typedef DDS_DCPSStruct_var < Sample_ChangeState_Response_> Sample_ChangeState_Response__var;
         typedef Sample_ChangeState_Response_&Sample_ChangeState_Response__out;
      }
   }
}




#endif
