//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Header_.h
//  Source: std_msgs\msg\dds_opensplice\Header_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _HEADER__H_
#define _HEADER__H_

#include "sacpp_mapping.h"
#include "Time_.h"
#include "std_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Header_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_std_msgs Header_
         {
               ::builtin_interfaces::msg::dds_::Time_ stamp_;
               DDS::String_mgr frame_id_;
         };

         typedef DDS_DCPSStruct_var < Header_> Header__var;
         typedef DDS_DCPSStruct_out < Header_> Header__out;
      }
   }
}




#endif
