//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Int16_.h
//  Source: std_msgs\msg\dds_opensplice\Int16_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _INT16__H_
#define _INT16__H_

#include "sacpp_mapping.h"
#include "std_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace std_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Int16_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_std_msgs Int16_
         {
               DDS::Short data_;
         };

         typedef DDS_DCPSStruct_var < Int16_> Int16__var;
         typedef Int16_&Int16__out;
      }
   }
}




#endif
