//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetMap_Request_.h
//  Source: nav_msgs\srv\dds_opensplice\GetMap_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETMAP_REQUEST__H_
#define _GETMAP_REQUEST__H_

#include "sacpp_mapping.h"
#include "nav_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace nav_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct GetMap_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_nav_msgs GetMap_Request_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < GetMap_Request_> GetMap_Request__var;
         typedef GetMap_Request_&GetMap_Request__out;
      }
   }
}




#endif
