//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetMap_Response_.h
//  Source: nav_msgs\srv\dds_opensplice\GetMap_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETMAP_RESPONSE__H_
#define _GETMAP_RESPONSE__H_

#include "sacpp_mapping.h"
#include "OccupancyGrid_.h"
#include "nav_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace nav_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct GetMap_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_nav_msgs GetMap_Response_
         {
               ::nav_msgs::msg::dds_::OccupancyGrid_ map_;
         };

         typedef DDS_DCPSStruct_var < GetMap_Response_> GetMap_Response__var;
         typedef DDS_DCPSStruct_out < GetMap_Response_> GetMap_Response__out;
      }
   }
}




#endif
