//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetPlan_Request_.h
//  Source: nav_msgs\srv\dds_opensplice\GetPlan_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETPLAN_REQUEST__H_
#define _GETPLAN_REQUEST__H_

#include "sacpp_mapping.h"
#include "PoseStamped_.h"
#include "nav_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace nav_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct GetPlan_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_nav_msgs GetPlan_Request_
         {
               ::geometry_msgs::msg::dds_::PoseStamped_ start_;
               ::geometry_msgs::msg::dds_::PoseStamped_ goal_;
               DDS::Float tolerance_;
         };

         typedef DDS_DCPSStruct_var < GetPlan_Request_> GetPlan_Request__var;
         typedef DDS_DCPSStruct_out < GetPlan_Request_> GetPlan_Request__out;
      }
   }
}




#endif
