//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: DynamicArrayPrimitivesNested_Dcps.h
//  Source: test_msgs\msg\dds_opensplice\DynamicArrayPrimitivesNested_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _DYNAMICARRAYPRIMITIVESNESTED_DCPS_H_
#define _DYNAMICARRAYPRIMITIVESNESTED_DCPS_H_

#include "sacpp_mapping.h"
#include "DynamicArrayPrimitivesNested_.h"
#include "dds_dcps.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_TypeSupportInterface;

         typedef DynamicArrayPrimitivesNested_TypeSupportInterface * DynamicArrayPrimitivesNested_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < DynamicArrayPrimitivesNested_TypeSupportInterface> DynamicArrayPrimitivesNested_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < DynamicArrayPrimitivesNested_TypeSupportInterface> DynamicArrayPrimitivesNested_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_DataWriter;

         typedef DynamicArrayPrimitivesNested_DataWriter * DynamicArrayPrimitivesNested_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < DynamicArrayPrimitivesNested_DataWriter> DynamicArrayPrimitivesNested_DataWriter_var;
         typedef DDS_DCPSInterface_out < DynamicArrayPrimitivesNested_DataWriter> DynamicArrayPrimitivesNested_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_DataReader;

         typedef DynamicArrayPrimitivesNested_DataReader * DynamicArrayPrimitivesNested_DataReader_ptr;
         typedef DDS_DCPSInterface_var < DynamicArrayPrimitivesNested_DataReader> DynamicArrayPrimitivesNested_DataReader_var;
         typedef DDS_DCPSInterface_out < DynamicArrayPrimitivesNested_DataReader> DynamicArrayPrimitivesNested_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_DataReaderView;

         typedef DynamicArrayPrimitivesNested_DataReaderView * DynamicArrayPrimitivesNested_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < DynamicArrayPrimitivesNested_DataReaderView> DynamicArrayPrimitivesNested_DataReaderView_var;
         typedef DDS_DCPSInterface_out < DynamicArrayPrimitivesNested_DataReaderView> DynamicArrayPrimitivesNested_DataReaderView_out;

         struct DynamicArrayPrimitivesNested_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < DynamicArrayPrimitivesNested_, struct DynamicArrayPrimitivesNested_Seq_uniq_> DynamicArrayPrimitivesNested_Seq;
         typedef DDS_DCPSSequence_var < DynamicArrayPrimitivesNested_Seq> DynamicArrayPrimitivesNested_Seq_var;
         typedef DDS_DCPSSequence_out < DynamicArrayPrimitivesNested_Seq> DynamicArrayPrimitivesNested_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef DynamicArrayPrimitivesNested_TypeSupportInterface_ptr _ptr_type;
            typedef DynamicArrayPrimitivesNested_TypeSupportInterface_var _var_type;

            static DynamicArrayPrimitivesNested_TypeSupportInterface_ptr _duplicate (DynamicArrayPrimitivesNested_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static DynamicArrayPrimitivesNested_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static DynamicArrayPrimitivesNested_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static DynamicArrayPrimitivesNested_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            DynamicArrayPrimitivesNested_TypeSupportInterface_ptr _this () { return this; }


         protected:
            DynamicArrayPrimitivesNested_TypeSupportInterface () {};
            ~DynamicArrayPrimitivesNested_TypeSupportInterface () {};
         private:
            DynamicArrayPrimitivesNested_TypeSupportInterface (const DynamicArrayPrimitivesNested_TypeSupportInterface &);
            DynamicArrayPrimitivesNested_TypeSupportInterface & operator = (const DynamicArrayPrimitivesNested_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef DynamicArrayPrimitivesNested_DataWriter_ptr _ptr_type;
            typedef DynamicArrayPrimitivesNested_DataWriter_var _var_type;

            static DynamicArrayPrimitivesNested_DataWriter_ptr _duplicate (DynamicArrayPrimitivesNested_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static DynamicArrayPrimitivesNested_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static DynamicArrayPrimitivesNested_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static DynamicArrayPrimitivesNested_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            DynamicArrayPrimitivesNested_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const DynamicArrayPrimitivesNested_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const DynamicArrayPrimitivesNested_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const DynamicArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const DynamicArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const DynamicArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const DynamicArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const DynamicArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const DynamicArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const DynamicArrayPrimitivesNested_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const DynamicArrayPrimitivesNested_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (DynamicArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const DynamicArrayPrimitivesNested_& instance_data) = 0;

         protected:
            DynamicArrayPrimitivesNested_DataWriter () {};
            ~DynamicArrayPrimitivesNested_DataWriter () {};
         private:
            DynamicArrayPrimitivesNested_DataWriter (const DynamicArrayPrimitivesNested_DataWriter &);
            DynamicArrayPrimitivesNested_DataWriter & operator = (const DynamicArrayPrimitivesNested_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef DynamicArrayPrimitivesNested_DataReader_ptr _ptr_type;
            typedef DynamicArrayPrimitivesNested_DataReader_var _var_type;

            static DynamicArrayPrimitivesNested_DataReader_ptr _duplicate (DynamicArrayPrimitivesNested_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static DynamicArrayPrimitivesNested_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static DynamicArrayPrimitivesNested_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static DynamicArrayPrimitivesNested_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            DynamicArrayPrimitivesNested_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (DynamicArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (DynamicArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (DynamicArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const DynamicArrayPrimitivesNested_& instance) = 0;

         protected:
            DynamicArrayPrimitivesNested_DataReader () {};
            ~DynamicArrayPrimitivesNested_DataReader () {};
         private:
            DynamicArrayPrimitivesNested_DataReader (const DynamicArrayPrimitivesNested_DataReader &);
            DynamicArrayPrimitivesNested_DataReader & operator = (const DynamicArrayPrimitivesNested_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef DynamicArrayPrimitivesNested_DataReaderView_ptr _ptr_type;
            typedef DynamicArrayPrimitivesNested_DataReaderView_var _var_type;

            static DynamicArrayPrimitivesNested_DataReaderView_ptr _duplicate (DynamicArrayPrimitivesNested_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static DynamicArrayPrimitivesNested_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static DynamicArrayPrimitivesNested_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static DynamicArrayPrimitivesNested_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            DynamicArrayPrimitivesNested_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (DynamicArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (DynamicArrayPrimitivesNested_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (DynamicArrayPrimitivesNested_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (DynamicArrayPrimitivesNested_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const DynamicArrayPrimitivesNested_& instance) = 0;

         protected:
            DynamicArrayPrimitivesNested_DataReaderView () {};
            ~DynamicArrayPrimitivesNested_DataReaderView () {};
         private:
            DynamicArrayPrimitivesNested_DataReaderView (const DynamicArrayPrimitivesNested_DataReaderView &);
            DynamicArrayPrimitivesNested_DataReaderView & operator = (const DynamicArrayPrimitivesNested_DataReaderView &);
         };

      }
   }
}




#endif
