//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: DynamicArrayNested_.h
//  Source: test_msgs\msg\dds_opensplice\DynamicArrayNested_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _DYNAMICARRAYNESTED__H_
#define _DYNAMICARRAYNESTED__H_

#include "sacpp_mapping.h"
#include "Primitives_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct DynamicArrayNested_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayNested_
         {
               struct _primitive_values__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < Primitives_, struct _primitive_values__seq_uniq_> _primitive_values__seq;
               typedef DDS_DCPSSequence_var < _primitive_values__seq> _primitive_values__seq_var;
               typedef DDS_DCPSSequence_out < _primitive_values__seq> _primitive_values__seq_out;
               _primitive_values__seq primitive_values_;
         };

         typedef DDS_DCPSStruct_var < DynamicArrayNested_> DynamicArrayNested__var;
         typedef DDS_DCPSStruct_out < DynamicArrayNested_> DynamicArrayNested__out;
      }
   }
}




#endif
