//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: DynamicArrayPrimitivesNested_.h
//  Source: test_msgs\msg\dds_opensplice\DynamicArrayPrimitivesNested_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _DYNAMICARRAYPRIMITIVESNESTED__H_
#define _DYNAMICARRAYPRIMITIVESNESTED__H_

#include "sacpp_mapping.h"
#include "DynamicArrayPrimitives_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct DynamicArrayPrimitivesNested_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs DynamicArrayPrimitivesNested_
         {
               struct _dynamic_array_primitive_values__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < DynamicArrayPrimitives_, struct _dynamic_array_primitive_values__seq_uniq_> _dynamic_array_primitive_values__seq;
               typedef DDS_DCPSSequence_var < _dynamic_array_primitive_values__seq> _dynamic_array_primitive_values__seq_var;
               typedef DDS_DCPSSequence_out < _dynamic_array_primitive_values__seq> _dynamic_array_primitive_values__seq_out;
               _dynamic_array_primitive_values__seq dynamic_array_primitive_values_;
         };

         typedef DDS_DCPSStruct_var < DynamicArrayPrimitivesNested_> DynamicArrayPrimitivesNested__var;
         typedef DDS_DCPSStruct_out < DynamicArrayPrimitivesNested_> DynamicArrayPrimitivesNested__out;
      }
   }
}




#endif
