#ifndef STATICARRAYPRIMITIVES_SPLTYPES_H
#define STATICARRAYPRIMITIVES_SPLTYPES_H

#include <c_base.h>
#include <c_misc.h>
#include <c_sync.h>
#include <c_collection.h>
#include <c_field.h>
#include <v_copyIn.h>

#include "ccpp_StaticArrayPrimitives_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"

extern c_metaObject __StaticArrayPrimitives__test_msgs__load (c_base base);

extern c_metaObject __StaticArrayPrimitives__test_msgs_msg__load (c_base base);

extern c_metaObject __StaticArrayPrimitives__test_msgs_msg_dds___load (c_base base);

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__boolean_array_3__load (c_base base);
typedef c_bool _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__boolean_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__octet_array_3__load (c_base base);
typedef c_octet _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__octet_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__char_array_3__load (c_base base);
typedef c_char _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__char_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__float_array_3__load (c_base base);
typedef c_float _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__float_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__double_array_3__load (c_base base);
typedef c_double _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__double_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__short_array_3__load (c_base base);
typedef c_short _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__short_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_short_array_3__load (c_base base);
typedef c_ushort _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_short_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__long_array_3__load (c_base base);
typedef c_long _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__long_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_long_array_3__load (c_base base);
typedef c_ulong _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_long_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__long_long_array_3__load (c_base base);
typedef c_longlong _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__long_long_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_long_long_array_3__load (c_base base);
typedef c_ulonglong _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_long_long_array_3[3];

extern c_metaObject __test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__string_array_3__load (c_base base);
typedef c_string _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__string_array_3[3];

extern const char *test_msgs_msg_dds__StaticArrayPrimitives__metaDescriptor[];
extern const int test_msgs_msg_dds__StaticArrayPrimitives__metaDescriptorArrLength;
extern const int test_msgs_msg_dds__StaticArrayPrimitives__metaDescriptorLength;
extern c_metaObject __test_msgs_msg_dds__StaticArrayPrimitives___load (c_base base);
struct _test_msgs_msg_dds__StaticArrayPrimitives_ ;
extern ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs v_copyin_result __test_msgs_msg_dds__StaticArrayPrimitives___copyIn(c_base base, const struct test_msgs::msg::dds_::StaticArrayPrimitives_ *from, struct _test_msgs_msg_dds__StaticArrayPrimitives_ *to);
extern ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs void __test_msgs_msg_dds__StaticArrayPrimitives___copyOut(const void *_from, void *_to);
struct _test_msgs_msg_dds__StaticArrayPrimitives_ {
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__boolean_array_3 bool_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__octet_array_3 byte_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__char_array_3 char_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__float_array_3 float32_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__double_array_3 float64_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__octet_array_3 int8_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__octet_array_3 uint8_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__short_array_3 int16_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_short_array_3 uint16_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__long_array_3 int32_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_long_array_3 uint32_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__long_long_array_3 int64_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__unsigned_long_long_array_3 uint64_values_;
    _test_msgs_msg_dds__test_msgs__StaticArrayPrimitives__string_array_3 string_values_;
};

#undef OS_API
#endif
