//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: StaticArrayPrimitives_Dcps.h
//  Source: test_msgs\msg\dds_opensplice\StaticArrayPrimitives_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _STATICARRAYPRIMITIVES_DCPS_H_
#define _STATICARRAYPRIMITIVES_DCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "StaticArrayPrimitives_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace msg
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitives_TypeSupportInterface;

         typedef StaticArrayPrimitives_TypeSupportInterface * StaticArrayPrimitives_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < StaticArrayPrimitives_TypeSupportInterface> StaticArrayPrimitives_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < StaticArrayPrimitives_TypeSupportInterface> StaticArrayPrimitives_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitives_DataWriter;

         typedef StaticArrayPrimitives_DataWriter * StaticArrayPrimitives_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < StaticArrayPrimitives_DataWriter> StaticArrayPrimitives_DataWriter_var;
         typedef DDS_DCPSInterface_out < StaticArrayPrimitives_DataWriter> StaticArrayPrimitives_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitives_DataReader;

         typedef StaticArrayPrimitives_DataReader * StaticArrayPrimitives_DataReader_ptr;
         typedef DDS_DCPSInterface_var < StaticArrayPrimitives_DataReader> StaticArrayPrimitives_DataReader_var;
         typedef DDS_DCPSInterface_out < StaticArrayPrimitives_DataReader> StaticArrayPrimitives_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitives_DataReaderView;

         typedef StaticArrayPrimitives_DataReaderView * StaticArrayPrimitives_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < StaticArrayPrimitives_DataReaderView> StaticArrayPrimitives_DataReaderView_var;
         typedef DDS_DCPSInterface_out < StaticArrayPrimitives_DataReaderView> StaticArrayPrimitives_DataReaderView_out;

         struct StaticArrayPrimitives_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < StaticArrayPrimitives_, struct StaticArrayPrimitives_Seq_uniq_> StaticArrayPrimitives_Seq;
         typedef DDS_DCPSSequence_var < StaticArrayPrimitives_Seq> StaticArrayPrimitives_Seq_var;
         typedef DDS_DCPSSequence_out < StaticArrayPrimitives_Seq> StaticArrayPrimitives_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitives_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef StaticArrayPrimitives_TypeSupportInterface_ptr _ptr_type;
            typedef StaticArrayPrimitives_TypeSupportInterface_var _var_type;

            static StaticArrayPrimitives_TypeSupportInterface_ptr _duplicate (StaticArrayPrimitives_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static StaticArrayPrimitives_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitives_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitives_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            StaticArrayPrimitives_TypeSupportInterface_ptr _this () { return this; }


         protected:
            StaticArrayPrimitives_TypeSupportInterface () {};
            ~StaticArrayPrimitives_TypeSupportInterface () {};
         private:
            StaticArrayPrimitives_TypeSupportInterface (const StaticArrayPrimitives_TypeSupportInterface &);
            StaticArrayPrimitives_TypeSupportInterface & operator = (const StaticArrayPrimitives_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitives_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef StaticArrayPrimitives_DataWriter_ptr _ptr_type;
            typedef StaticArrayPrimitives_DataWriter_var _var_type;

            static StaticArrayPrimitives_DataWriter_ptr _duplicate (StaticArrayPrimitives_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static StaticArrayPrimitives_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitives_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitives_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            StaticArrayPrimitives_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const StaticArrayPrimitives_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const StaticArrayPrimitives_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const StaticArrayPrimitives_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const StaticArrayPrimitives_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const StaticArrayPrimitives_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const StaticArrayPrimitives_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const StaticArrayPrimitives_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const StaticArrayPrimitives_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const StaticArrayPrimitives_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const StaticArrayPrimitives_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (StaticArrayPrimitives_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const StaticArrayPrimitives_& instance_data) = 0;

         protected:
            StaticArrayPrimitives_DataWriter () {};
            ~StaticArrayPrimitives_DataWriter () {};
         private:
            StaticArrayPrimitives_DataWriter (const StaticArrayPrimitives_DataWriter &);
            StaticArrayPrimitives_DataWriter & operator = (const StaticArrayPrimitives_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitives_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef StaticArrayPrimitives_DataReader_ptr _ptr_type;
            typedef StaticArrayPrimitives_DataReader_var _var_type;

            static StaticArrayPrimitives_DataReader_ptr _duplicate (StaticArrayPrimitives_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static StaticArrayPrimitives_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitives_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitives_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            StaticArrayPrimitives_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (StaticArrayPrimitives_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (StaticArrayPrimitives_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (StaticArrayPrimitives_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const StaticArrayPrimitives_& instance) = 0;

         protected:
            StaticArrayPrimitives_DataReader () {};
            ~StaticArrayPrimitives_DataReader () {};
         private:
            StaticArrayPrimitives_DataReader (const StaticArrayPrimitives_DataReader &);
            StaticArrayPrimitives_DataReader & operator = (const StaticArrayPrimitives_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs StaticArrayPrimitives_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef StaticArrayPrimitives_DataReaderView_ptr _ptr_type;
            typedef StaticArrayPrimitives_DataReaderView_var _var_type;

            static StaticArrayPrimitives_DataReaderView_ptr _duplicate (StaticArrayPrimitives_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static StaticArrayPrimitives_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitives_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static StaticArrayPrimitives_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            StaticArrayPrimitives_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (StaticArrayPrimitives_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (StaticArrayPrimitives_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (StaticArrayPrimitives_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (StaticArrayPrimitives_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const StaticArrayPrimitives_& instance) = 0;

         protected:
            StaticArrayPrimitives_DataReaderView () {};
            ~StaticArrayPrimitives_DataReaderView () {};
         private:
            StaticArrayPrimitives_DataReaderView (const StaticArrayPrimitives_DataReaderView &);
            StaticArrayPrimitives_DataReaderView & operator = (const StaticArrayPrimitives_DataReaderView &);
         };

      }
   }
}




#endif
