//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetMapROI_Response_Dcps.h
//  Source: map_msgs\srv\dds_opensplice\GetMapROI_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETMAPROI_RESPONSE_DCPS_H_
#define _GETMAPROI_RESPONSE_DCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "GetMapROI_Response_.h"
#include "map_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace map_msgs
{
   namespace srv
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetMapROI_Response_TypeSupportInterface;

         typedef GetMapROI_Response_TypeSupportInterface * GetMapROI_Response_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < GetMapROI_Response_TypeSupportInterface> GetMapROI_Response_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < GetMapROI_Response_TypeSupportInterface> GetMapROI_Response_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetMapROI_Response_DataWriter;

         typedef GetMapROI_Response_DataWriter * GetMapROI_Response_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < GetMapROI_Response_DataWriter> GetMapROI_Response_DataWriter_var;
         typedef DDS_DCPSInterface_out < GetMapROI_Response_DataWriter> GetMapROI_Response_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetMapROI_Response_DataReader;

         typedef GetMapROI_Response_DataReader * GetMapROI_Response_DataReader_ptr;
         typedef DDS_DCPSInterface_var < GetMapROI_Response_DataReader> GetMapROI_Response_DataReader_var;
         typedef DDS_DCPSInterface_out < GetMapROI_Response_DataReader> GetMapROI_Response_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetMapROI_Response_DataReaderView;

         typedef GetMapROI_Response_DataReaderView * GetMapROI_Response_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < GetMapROI_Response_DataReaderView> GetMapROI_Response_DataReaderView_var;
         typedef DDS_DCPSInterface_out < GetMapROI_Response_DataReaderView> GetMapROI_Response_DataReaderView_out;

         struct GetMapROI_Response_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < GetMapROI_Response_, struct GetMapROI_Response_Seq_uniq_> GetMapROI_Response_Seq;
         typedef DDS_DCPSSequence_var < GetMapROI_Response_Seq> GetMapROI_Response_Seq_var;
         typedef DDS_DCPSSequence_out < GetMapROI_Response_Seq> GetMapROI_Response_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetMapROI_Response_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef GetMapROI_Response_TypeSupportInterface_ptr _ptr_type;
            typedef GetMapROI_Response_TypeSupportInterface_var _var_type;

            static GetMapROI_Response_TypeSupportInterface_ptr _duplicate (GetMapROI_Response_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetMapROI_Response_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static GetMapROI_Response_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetMapROI_Response_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            GetMapROI_Response_TypeSupportInterface_ptr _this () { return this; }


         protected:
            GetMapROI_Response_TypeSupportInterface () {};
            ~GetMapROI_Response_TypeSupportInterface () {};
         private:
            GetMapROI_Response_TypeSupportInterface (const GetMapROI_Response_TypeSupportInterface &);
            GetMapROI_Response_TypeSupportInterface & operator = (const GetMapROI_Response_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetMapROI_Response_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef GetMapROI_Response_DataWriter_ptr _ptr_type;
            typedef GetMapROI_Response_DataWriter_var _var_type;

            static GetMapROI_Response_DataWriter_ptr _duplicate (GetMapROI_Response_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetMapROI_Response_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static GetMapROI_Response_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetMapROI_Response_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            GetMapROI_Response_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const GetMapROI_Response_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const GetMapROI_Response_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const GetMapROI_Response_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const GetMapROI_Response_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const GetMapROI_Response_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const GetMapROI_Response_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const GetMapROI_Response_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const GetMapROI_Response_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const GetMapROI_Response_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const GetMapROI_Response_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (GetMapROI_Response_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetMapROI_Response_& instance_data) = 0;

         protected:
            GetMapROI_Response_DataWriter () {};
            ~GetMapROI_Response_DataWriter () {};
         private:
            GetMapROI_Response_DataWriter (const GetMapROI_Response_DataWriter &);
            GetMapROI_Response_DataWriter & operator = (const GetMapROI_Response_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetMapROI_Response_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef GetMapROI_Response_DataReader_ptr _ptr_type;
            typedef GetMapROI_Response_DataReader_var _var_type;

            static GetMapROI_Response_DataReader_ptr _duplicate (GetMapROI_Response_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetMapROI_Response_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static GetMapROI_Response_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetMapROI_Response_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            GetMapROI_Response_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (GetMapROI_Response_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (GetMapROI_Response_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (GetMapROI_Response_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetMapROI_Response_& instance) = 0;

         protected:
            GetMapROI_Response_DataReader () {};
            ~GetMapROI_Response_DataReader () {};
         private:
            GetMapROI_Response_DataReader (const GetMapROI_Response_DataReader &);
            GetMapROI_Response_DataReader & operator = (const GetMapROI_Response_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetMapROI_Response_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef GetMapROI_Response_DataReaderView_ptr _ptr_type;
            typedef GetMapROI_Response_DataReaderView_var _var_type;

            static GetMapROI_Response_DataReaderView_ptr _duplicate (GetMapROI_Response_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static GetMapROI_Response_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static GetMapROI_Response_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static GetMapROI_Response_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            GetMapROI_Response_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (GetMapROI_Response_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (GetMapROI_Response_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (GetMapROI_Response_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (GetMapROI_Response_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const GetMapROI_Response_& instance) = 0;

         protected:
            GetMapROI_Response_DataReaderView () {};
            ~GetMapROI_Response_DataReaderView () {};
         private:
            GetMapROI_Response_DataReaderView (const GetMapROI_Response_DataReaderView &);
            GetMapROI_Response_DataReaderView & operator = (const GetMapROI_Response_DataReaderView &);
         };

      }
   }
}




#endif
