//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetPointMap_Response_.h
//  Source: map_msgs\srv\dds_opensplice\GetPointMap_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETPOINTMAP_RESPONSE__H_
#define _GETPOINTMAP_RESPONSE__H_

#include "sacpp_mapping.h"
#include "PointCloud2_.h"
#include "map_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace map_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct GetPointMap_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs GetPointMap_Response_
         {
               ::sensor_msgs::msg::dds_::PointCloud2_ map_;
         };

         typedef DDS_DCPSStruct_var < GetPointMap_Response_> GetPointMap_Response__var;
         typedef DDS_DCPSStruct_out < GetPointMap_Response_> GetPointMap_Response__out;
      }
   }
}




#endif
