//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ProjectedMapsInfo_Request_Dcps.h
//  Source: map_msgs\srv\dds_opensplice\ProjectedMapsInfo_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _PROJECTEDMAPSINFO_REQUEST_DCPS_H_
#define _PROJECTEDMAPSINFO_REQUEST_DCPS_H_

#include "sacpp_mapping.h"
#include "ProjectedMapsInfo_Request_.h"
#include "dds_dcps.h"
#include "map_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace map_msgs
{
   namespace srv
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs ProjectedMapsInfo_Request_TypeSupportInterface;

         typedef ProjectedMapsInfo_Request_TypeSupportInterface * ProjectedMapsInfo_Request_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < ProjectedMapsInfo_Request_TypeSupportInterface> ProjectedMapsInfo_Request_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < ProjectedMapsInfo_Request_TypeSupportInterface> ProjectedMapsInfo_Request_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs ProjectedMapsInfo_Request_DataWriter;

         typedef ProjectedMapsInfo_Request_DataWriter * ProjectedMapsInfo_Request_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < ProjectedMapsInfo_Request_DataWriter> ProjectedMapsInfo_Request_DataWriter_var;
         typedef DDS_DCPSInterface_out < ProjectedMapsInfo_Request_DataWriter> ProjectedMapsInfo_Request_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs ProjectedMapsInfo_Request_DataReader;

         typedef ProjectedMapsInfo_Request_DataReader * ProjectedMapsInfo_Request_DataReader_ptr;
         typedef DDS_DCPSInterface_var < ProjectedMapsInfo_Request_DataReader> ProjectedMapsInfo_Request_DataReader_var;
         typedef DDS_DCPSInterface_out < ProjectedMapsInfo_Request_DataReader> ProjectedMapsInfo_Request_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs ProjectedMapsInfo_Request_DataReaderView;

         typedef ProjectedMapsInfo_Request_DataReaderView * ProjectedMapsInfo_Request_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < ProjectedMapsInfo_Request_DataReaderView> ProjectedMapsInfo_Request_DataReaderView_var;
         typedef DDS_DCPSInterface_out < ProjectedMapsInfo_Request_DataReaderView> ProjectedMapsInfo_Request_DataReaderView_out;

         struct ProjectedMapsInfo_Request_Seq_uniq_ {};
         typedef DDS_DCPSUVLSeq < ProjectedMapsInfo_Request_, struct ProjectedMapsInfo_Request_Seq_uniq_> ProjectedMapsInfo_Request_Seq;
         typedef DDS_DCPSSequence_var < ProjectedMapsInfo_Request_Seq> ProjectedMapsInfo_Request_Seq_var;
         typedef DDS_DCPSSequence_out < ProjectedMapsInfo_Request_Seq> ProjectedMapsInfo_Request_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs ProjectedMapsInfo_Request_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef ProjectedMapsInfo_Request_TypeSupportInterface_ptr _ptr_type;
            typedef ProjectedMapsInfo_Request_TypeSupportInterface_var _var_type;

            static ProjectedMapsInfo_Request_TypeSupportInterface_ptr _duplicate (ProjectedMapsInfo_Request_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static ProjectedMapsInfo_Request_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static ProjectedMapsInfo_Request_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static ProjectedMapsInfo_Request_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            ProjectedMapsInfo_Request_TypeSupportInterface_ptr _this () { return this; }


         protected:
            ProjectedMapsInfo_Request_TypeSupportInterface () {};
            ~ProjectedMapsInfo_Request_TypeSupportInterface () {};
         private:
            ProjectedMapsInfo_Request_TypeSupportInterface (const ProjectedMapsInfo_Request_TypeSupportInterface &);
            ProjectedMapsInfo_Request_TypeSupportInterface & operator = (const ProjectedMapsInfo_Request_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs ProjectedMapsInfo_Request_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef ProjectedMapsInfo_Request_DataWriter_ptr _ptr_type;
            typedef ProjectedMapsInfo_Request_DataWriter_var _var_type;

            static ProjectedMapsInfo_Request_DataWriter_ptr _duplicate (ProjectedMapsInfo_Request_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static ProjectedMapsInfo_Request_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static ProjectedMapsInfo_Request_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static ProjectedMapsInfo_Request_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            ProjectedMapsInfo_Request_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const ProjectedMapsInfo_Request_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const ProjectedMapsInfo_Request_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const ProjectedMapsInfo_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const ProjectedMapsInfo_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const ProjectedMapsInfo_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const ProjectedMapsInfo_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const ProjectedMapsInfo_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const ProjectedMapsInfo_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const ProjectedMapsInfo_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const ProjectedMapsInfo_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (ProjectedMapsInfo_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const ProjectedMapsInfo_Request_& instance_data) = 0;

         protected:
            ProjectedMapsInfo_Request_DataWriter () {};
            ~ProjectedMapsInfo_Request_DataWriter () {};
         private:
            ProjectedMapsInfo_Request_DataWriter (const ProjectedMapsInfo_Request_DataWriter &);
            ProjectedMapsInfo_Request_DataWriter & operator = (const ProjectedMapsInfo_Request_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs ProjectedMapsInfo_Request_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef ProjectedMapsInfo_Request_DataReader_ptr _ptr_type;
            typedef ProjectedMapsInfo_Request_DataReader_var _var_type;

            static ProjectedMapsInfo_Request_DataReader_ptr _duplicate (ProjectedMapsInfo_Request_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static ProjectedMapsInfo_Request_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static ProjectedMapsInfo_Request_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static ProjectedMapsInfo_Request_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            ProjectedMapsInfo_Request_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (ProjectedMapsInfo_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (ProjectedMapsInfo_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (ProjectedMapsInfo_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const ProjectedMapsInfo_Request_& instance) = 0;

         protected:
            ProjectedMapsInfo_Request_DataReader () {};
            ~ProjectedMapsInfo_Request_DataReader () {};
         private:
            ProjectedMapsInfo_Request_DataReader (const ProjectedMapsInfo_Request_DataReader &);
            ProjectedMapsInfo_Request_DataReader & operator = (const ProjectedMapsInfo_Request_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs ProjectedMapsInfo_Request_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef ProjectedMapsInfo_Request_DataReaderView_ptr _ptr_type;
            typedef ProjectedMapsInfo_Request_DataReaderView_var _var_type;

            static ProjectedMapsInfo_Request_DataReaderView_ptr _duplicate (ProjectedMapsInfo_Request_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static ProjectedMapsInfo_Request_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static ProjectedMapsInfo_Request_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static ProjectedMapsInfo_Request_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            ProjectedMapsInfo_Request_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (ProjectedMapsInfo_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (ProjectedMapsInfo_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (ProjectedMapsInfo_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (ProjectedMapsInfo_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const ProjectedMapsInfo_Request_& instance) = 0;

         protected:
            ProjectedMapsInfo_Request_DataReaderView () {};
            ~ProjectedMapsInfo_Request_DataReaderView () {};
         private:
            ProjectedMapsInfo_Request_DataReaderView (const ProjectedMapsInfo_Request_DataReaderView &);
            ProjectedMapsInfo_Request_DataReaderView & operator = (const ProjectedMapsInfo_Request_DataReaderView &);
         };

      }
   }
}




#endif
