//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SaveMap_Request_.h
//  Source: map_msgs\srv\dds_opensplice\SaveMap_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SAVEMAP_REQUEST__H_
#define _SAVEMAP_REQUEST__H_

#include "sacpp_mapping.h"
#include "String_.h"
#include "map_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace map_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct SaveMap_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs SaveMap_Request_
         {
               ::std_msgs::msg::dds_::String_ filename_;
         };

         typedef DDS_DCPSStruct_var < SaveMap_Request_> SaveMap_Request__var;
         typedef DDS_DCPSStruct_out < SaveMap_Request_> SaveMap_Request__out;
      }
   }
}




#endif
