//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SaveMap_Response_.h
//  Source: map_msgs\srv\dds_opensplice\SaveMap_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SAVEMAP_RESPONSE__H_
#define _SAVEMAP_RESPONSE__H_

#include "sacpp_mapping.h"
#include "map_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace map_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct SaveMap_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_map_msgs SaveMap_Response_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < SaveMap_Response_> SaveMap_Response__var;
         typedef SaveMap_Response_&SaveMap_Response__out;
      }
   }
}




#endif
