//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: TransitionEvent_.h
//  Source: lifecycle_msgs\msg\dds_opensplice\TransitionEvent_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _TRANSITIONEVENT__H_
#define _TRANSITIONEVENT__H_

#include "sacpp_mapping.h"
#include "Transition_.h"
#include "State_.h"
#include "lifecycle_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace lifecycle_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct TransitionEvent_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_lifecycle_msgs TransitionEvent_
         {
               DDS::ULongLong timestamp_;
               Transition_ transition_;
               State_ start_state_;
               State_ goal_state_;
         };

         typedef DDS_DCPSStruct_var < TransitionEvent_> TransitionEvent__var;
         typedef DDS_DCPSStruct_out < TransitionEvent_> TransitionEvent__out;
      }
   }
}




#endif
