//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_Empty_Response_.h
//  Source: test_msgs\srv\dds_opensplice\Sample_Empty_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SAMPLE_EMPTY_RESPONSE__H_
#define _SAMPLE_EMPTY_RESPONSE__H_

#include "sacpp_mapping.h"
#include "Empty_Response_.h"
#include "test_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace test_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct Sample_Empty_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_test_msgs Sample_Empty_Response_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               Empty_Response_ response_;
         };

         typedef DDS_DCPSStruct_var < Sample_Empty_Response_> Sample_Empty_Response__var;
         typedef Sample_Empty_Response_&Sample_Empty_Response__out;
      }
   }
}




#endif
