//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: InteractiveMarkerPose_.h
//  Source: visualization_msgs\msg\dds_opensplice\InteractiveMarkerPose_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _INTERACTIVEMARKERPOSE__H_
#define _INTERACTIVEMARKERPOSE__H_

#include "sacpp_mapping.h"
#include "Pose_.h"
#include "Header_.h"
#include "visualization_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace visualization_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct InteractiveMarkerPose_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_visualization_msgs InteractiveMarkerPose_
         {
               ::std_msgs::msg::dds_::Header_ header_;
               ::geometry_msgs::msg::dds_::Pose_ pose_;
               DDS::String_mgr name_;
         };

         typedef DDS_DCPSStruct_var < InteractiveMarkerPose_> InteractiveMarkerPose__var;
         typedef DDS_DCPSStruct_out < InteractiveMarkerPose_> InteractiveMarkerPose__out;
      }
   }
}




#endif
