//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: InteractiveMarkerControl_.h
//  Source: visualization_msgs\msg\dds_opensplice\InteractiveMarkerControl_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _INTERACTIVEMARKERCONTROL__H_
#define _INTERACTIVEMARKERCONTROL__H_

#include "sacpp_mapping.h"
#include "Marker_.h"
#include "Quaternion_.h"
#include "visualization_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace visualization_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct InteractiveMarkerControl_;
         const DDS::Octet InteractiveMarkerControl__INHERIT = (DDS::Octet) 0;
         const DDS::Octet InteractiveMarkerControl__FIXED = (DDS::Octet) 1;
         const DDS::Octet InteractiveMarkerControl__VIEW_FACING = (DDS::Octet) 2;
         const DDS::Octet InteractiveMarkerControl__NONE = (DDS::Octet) 0;
         const DDS::Octet InteractiveMarkerControl__MENU = (DDS::Octet) 1;
         const DDS::Octet InteractiveMarkerControl__BUTTON = (DDS::Octet) 2;
         const DDS::Octet InteractiveMarkerControl__MOVE_AXIS = (DDS::Octet) 3;
         const DDS::Octet InteractiveMarkerControl__MOVE_PLANE = (DDS::Octet) 4;
         const DDS::Octet InteractiveMarkerControl__ROTATE_AXIS = (DDS::Octet) 5;
         const DDS::Octet InteractiveMarkerControl__MOVE_ROTATE = (DDS::Octet) 6;
         const DDS::Octet InteractiveMarkerControl__MOVE_3D = (DDS::Octet) 7;
         const DDS::Octet InteractiveMarkerControl__ROTATE_3D = (DDS::Octet) 8;
         const DDS::Octet InteractiveMarkerControl__MOVE_ROTATE_3D = (DDS::Octet) 9;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_visualization_msgs InteractiveMarkerControl_
         {
               struct _markers__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < Marker_, struct _markers__seq_uniq_> _markers__seq;
               typedef DDS_DCPSSequence_var < _markers__seq> _markers__seq_var;
               typedef DDS_DCPSSequence_out < _markers__seq> _markers__seq_out;
               DDS::String_mgr name_;
               ::geometry_msgs::msg::dds_::Quaternion_ orientation_;
               DDS::Octet orientation_mode_;
               DDS::Octet interaction_mode_;
               DDS::Boolean always_visible_;
               _markers__seq markers_;
               DDS::Boolean independent_marker_orientation_;
               DDS::String_mgr description_;
         };

         typedef DDS_DCPSStruct_var < InteractiveMarkerControl_> InteractiveMarkerControl__var;
         typedef DDS_DCPSStruct_out < InteractiveMarkerControl_> InteractiveMarkerControl__out;
      }
   }
}




#endif
