//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: InteractiveMarker_.h
//  Source: visualization_msgs\msg\dds_opensplice\InteractiveMarker_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _INTERACTIVEMARKER__H_
#define _INTERACTIVEMARKER__H_

#include "sacpp_mapping.h"
#include "InteractiveMarkerControl_.h"
#include "Pose_.h"
#include "Quaternion_.h"
#include "MenuEntry_.h"
#include "Header_.h"
#include "visualization_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace visualization_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct InteractiveMarker_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_visualization_msgs InteractiveMarker_
         {
               struct _menu_entries__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < MenuEntry_, struct _menu_entries__seq_uniq_> _menu_entries__seq;
               typedef DDS_DCPSSequence_var < _menu_entries__seq> _menu_entries__seq_var;
               typedef DDS_DCPSSequence_out < _menu_entries__seq> _menu_entries__seq_out;
               struct _controls__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < InteractiveMarkerControl_, struct _controls__seq_uniq_> _controls__seq;
               typedef DDS_DCPSSequence_var < _controls__seq> _controls__seq_var;
               typedef DDS_DCPSSequence_out < _controls__seq> _controls__seq_out;
               ::std_msgs::msg::dds_::Header_ header_;
               ::geometry_msgs::msg::dds_::Pose_ pose_;
               DDS::String_mgr name_;
               DDS::String_mgr description_;
               DDS::Float scale_;
               _menu_entries__seq menu_entries_;
               _controls__seq controls_;
         };

         typedef DDS_DCPSStruct_var < InteractiveMarker_> InteractiveMarker__var;
         typedef DDS_DCPSStruct_out < InteractiveMarker_> InteractiveMarker__out;
      }
   }
}




#endif
