//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: MenuEntry_.h
//  Source: visualization_msgs\msg\dds_opensplice\MenuEntry_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _MENUENTRY__H_
#define _MENUENTRY__H_

#include "sacpp_mapping.h"
#include "visualization_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace visualization_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct MenuEntry_;
         const DDS::Octet MenuEntry__FEEDBACK = (DDS::Octet) 0;
         const DDS::Octet MenuEntry__ROSRUN = (DDS::Octet) 1;
         const DDS::Octet MenuEntry__ROSLAUNCH = (DDS::Octet) 2;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_visualization_msgs MenuEntry_
         {
               DDS::ULong id_;
               DDS::ULong parent_id_;
               DDS::String_mgr title_;
               DDS::String_mgr command_;
               DDS::Octet command_type_;
         };

         typedef DDS_DCPSStruct_var < MenuEntry_> MenuEntry__var;
         typedef DDS_DCPSStruct_out < MenuEntry_> MenuEntry__out;
      }
   }
}




#endif
