//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Empty_Response_.h
//  Source: std_srvs\srv\dds_opensplice\Empty_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _EMPTY_RESPONSE__H_
#define _EMPTY_RESPONSE__H_

#include "sacpp_mapping.h"
#include "std_srvs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace std_srvs
{
   namespace srv
   {
      namespace dds_
      {
         struct Empty_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_std_srvs Empty_Response_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < Empty_Response_> Empty_Response__var;
         typedef Empty_Response_&Empty_Response__out;
      }
   }
}




#endif
