//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SetBool_Response_.h
//  Source: std_srvs\srv\dds_opensplice\SetBool_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SETBOOL_RESPONSE__H_
#define _SETBOOL_RESPONSE__H_

#include "sacpp_mapping.h"
#include "std_srvs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace std_srvs
{
   namespace srv
   {
      namespace dds_
      {
         struct SetBool_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_std_srvs SetBool_Response_
         {
               DDS::Boolean success_;
               DDS::String_mgr message_;
         };

         typedef DDS_DCPSStruct_var < SetBool_Response_> SetBool_Response__var;
         typedef DDS_DCPSStruct_out < SetBool_Response_> SetBool_Response__out;
      }
   }
}




#endif
