//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Trigger_Request_.h
//  Source: std_srvs\srv\dds_opensplice\Trigger_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _TRIGGER_REQUEST__H_
#define _TRIGGER_REQUEST__H_

#include "sacpp_mapping.h"
#include "std_srvs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace std_srvs
{
   namespace srv
   {
      namespace dds_
      {
         struct Trigger_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_std_srvs Trigger_Request_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < Trigger_Request_> Trigger_Request__var;
         typedef Trigger_Request_&Trigger_Request__out;
      }
   }
}




#endif
