//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: LoadNode_Request_.h
//  Source: composition\srv\dds_opensplice\LoadNode_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _LOADNODE_REQUEST__H_
#define _LOADNODE_REQUEST__H_

#include "sacpp_mapping.h"
#include "composition/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace composition
{
   namespace srv
   {
      namespace dds_
      {
         struct LoadNode_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_composition LoadNode_Request_
         {
               DDS::String_mgr package_name_;
               DDS::String_mgr plugin_name_;
         };

         typedef DDS_DCPSStruct_var < LoadNode_Request_> LoadNode_Request__var;
         typedef DDS_DCPSStruct_out < LoadNode_Request_> LoadNode_Request__out;
      }
   }
}




#endif
