//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Accel_.h
//  Source: geometry_msgs\msg\dds_opensplice\Accel_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _ACCEL__H_
#define _ACCEL__H_

#include "sacpp_mapping.h"
#include "Vector3_.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Accel_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs Accel_
         {
               Vector3_ linear_;
               Vector3_ angular_;
         };

         typedef DDS_DCPSStruct_var < Accel_> Accel__var;
         typedef Accel_&Accel__out;
      }
   }
}




#endif
