//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: AccelWithCovarianceStamped_.h
//  Source: geometry_msgs\msg\dds_opensplice\AccelWithCovarianceStamped_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _ACCELWITHCOVARIANCESTAMPED__H_
#define _ACCELWITHCOVARIANCESTAMPED__H_

#include "sacpp_mapping.h"
#include "AccelWithCovariance_.h"
#include "Header_.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct AccelWithCovarianceStamped_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs AccelWithCovarianceStamped_
         {
               ::std_msgs::msg::dds_::Header_ header_;
               AccelWithCovariance_ accel_;
         };

         typedef DDS_DCPSStruct_var < AccelWithCovarianceStamped_> AccelWithCovarianceStamped__var;
         typedef DDS_DCPSStruct_out < AccelWithCovarianceStamped_> AccelWithCovarianceStamped__out;
      }
   }
}




#endif
