//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Point_.h
//  Source: geometry_msgs\msg\dds_opensplice\Point_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _POINT__H_
#define _POINT__H_

#include "sacpp_mapping.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Point_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs Point_
         {
               DDS::Double x_;
               DDS::Double y_;
               DDS::Double z_;
         };

         typedef DDS_DCPSStruct_var < Point_> Point__var;
         typedef Point_&Point__out;
      }
   }
}




#endif
