//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: PoseWithCovarianceStamped_.h
//  Source: geometry_msgs\msg\dds_opensplice\PoseWithCovarianceStamped_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _POSEWITHCOVARIANCESTAMPED__H_
#define _POSEWITHCOVARIANCESTAMPED__H_

#include "sacpp_mapping.h"
#include "PoseWithCovariance_.h"
#include "Header_.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct PoseWithCovarianceStamped_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs PoseWithCovarianceStamped_
         {
               ::std_msgs::msg::dds_::Header_ header_;
               PoseWithCovariance_ pose_;
         };

         typedef DDS_DCPSStruct_var < PoseWithCovarianceStamped_> PoseWithCovarianceStamped__var;
         typedef DDS_DCPSStruct_out < PoseWithCovarianceStamped_> PoseWithCovarianceStamped__out;
      }
   }
}




#endif
