//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Pose2D_.h
//  Source: geometry_msgs\msg\dds_opensplice\Pose2D_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _POSE2D__H_
#define _POSE2D__H_

#include "sacpp_mapping.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Pose2D_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs Pose2D_
         {
               DDS::Double x_;
               DDS::Double y_;
               DDS::Double theta_;
         };

         typedef DDS_DCPSStruct_var < Pose2D_> Pose2D__var;
         typedef Pose2D_&Pose2D__out;
      }
   }
}




#endif
