//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Transform_.h
//  Source: geometry_msgs\msg\dds_opensplice\Transform_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _TRANSFORM__H_
#define _TRANSFORM__H_

#include "sacpp_mapping.h"
#include "Vector3_.h"
#include "Quaternion_.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Transform_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs Transform_
         {
               Vector3_ translation_;
               Quaternion_ rotation_;
         };

         typedef DDS_DCPSStruct_var < Transform_> Transform__var;
         typedef Transform_&Transform__out;
      }
   }
}




#endif
