//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: TwistWithCovariance_.h
//  Source: geometry_msgs\msg\dds_opensplice\TwistWithCovariance_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _TWISTWITHCOVARIANCE__H_
#define _TWISTWITHCOVARIANCE__H_

#include "sacpp_mapping.h"
#include "Twist_.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct TwistWithCovariance_;
         typedef DDS::Double geometry_msgs__TwistWithCovariance__double_array_36_slice;
         typedef DDS::Double geometry_msgs__TwistWithCovariance__double_array_36[36];
         typedef geometry_msgs__TwistWithCovariance__double_array_36 geometry_msgs__TwistWithCovariance__double_array_36_out;
         ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs extern geometry_msgs__TwistWithCovariance__double_array_36_slice * geometry_msgs__TwistWithCovariance__double_array_36_alloc ();
         ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs extern void geometry_msgs__TwistWithCovariance__double_array_36_free (geometry_msgs__TwistWithCovariance__double_array_36_slice *);
         ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs extern void geometry_msgs__TwistWithCovariance__double_array_36_copy (geometry_msgs__TwistWithCovariance__double_array_36_slice* to, const geometry_msgs__TwistWithCovariance__double_array_36_slice* from);
         ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs extern geometry_msgs__TwistWithCovariance__double_array_36_slice *geometry_msgs__TwistWithCovariance__double_array_36_dup (const geometry_msgs__TwistWithCovariance__double_array_36_slice* from);

         struct geometry_msgs__TwistWithCovariance__double_array_36_uniq_ {};
         typedef DDS_DCPS_FArray_var< geometry_msgs__TwistWithCovariance__double_array_36, geometry_msgs__TwistWithCovariance__double_array_36_slice, struct geometry_msgs__TwistWithCovariance__double_array_36_uniq_> geometry_msgs__TwistWithCovariance__double_array_36_var;
         typedef DDS_DCPS_Array_forany< geometry_msgs__TwistWithCovariance__double_array_36, geometry_msgs__TwistWithCovariance__double_array_36_slice, struct geometry_msgs__TwistWithCovariance__double_array_36_uniq_> geometry_msgs__TwistWithCovariance__double_array_36_forany;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs TwistWithCovariance_
         {
               Twist_ twist_;
               geometry_msgs__TwistWithCovariance__double_array_36 covariance_;
         };

         typedef DDS_DCPSStruct_var < TwistWithCovariance_> TwistWithCovariance__var;
         typedef TwistWithCovariance_&TwistWithCovariance__out;
      }
   }
}
template <>
geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_slice* DDS_DCPS_ArrayHelper < geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36, geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_slice, geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36, geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_slice, geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_uniq_>::copy (geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_slice *to, const geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_slice* from);
template <>
void DDS_DCPS_ArrayHelper < geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36, geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_slice, geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_uniq_>::free (geometry_msgs::msg::dds_::geometry_msgs__TwistWithCovariance__double_array_36_slice *ptr);




#endif
