//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: TwistWithCovarianceStamped_.h
//  Source: geometry_msgs\msg\dds_opensplice\TwistWithCovarianceStamped_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _TWISTWITHCOVARIANCESTAMPED__H_
#define _TWISTWITHCOVARIANCESTAMPED__H_

#include "sacpp_mapping.h"
#include "TwistWithCovariance_.h"
#include "Header_.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct TwistWithCovarianceStamped_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs TwistWithCovarianceStamped_
         {
               ::std_msgs::msg::dds_::Header_ header_;
               TwistWithCovariance_ twist_;
         };

         typedef DDS_DCPSStruct_var < TwistWithCovarianceStamped_> TwistWithCovarianceStamped__var;
         typedef DDS_DCPSStruct_out < TwistWithCovarianceStamped_> TwistWithCovarianceStamped__out;
      }
   }
}




#endif
