//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Wrench_.h
//  Source: geometry_msgs\msg\dds_opensplice\Wrench_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _WRENCH__H_
#define _WRENCH__H_

#include "sacpp_mapping.h"
#include "Vector3_.h"
#include "geometry_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace geometry_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Wrench_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_geometry_msgs Wrench_
         {
               Vector3_ force_;
               Vector3_ torque_;
         };

         typedef DDS_DCPSStruct_var < Wrench_> Wrench__var;
         typedef Wrench_&Wrench__out;
      }
   }
}




#endif
