//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: FrameGraph_Request_.h
//  Source: tf2_msgs\srv\dds_opensplice\FrameGraph_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _FRAMEGRAPH_REQUEST__H_
#define _FRAMEGRAPH_REQUEST__H_

#include "sacpp_mapping.h"
#include "tf2_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace tf2_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct FrameGraph_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_
         {
               DDS::Boolean dummy;
         };

         typedef DDS_DCPSStruct_var < FrameGraph_Request_> FrameGraph_Request__var;
         typedef FrameGraph_Request_&FrameGraph_Request__out;
      }
   }
}




#endif
