//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: FrameGraph_Request_Dcps.h
//  Source: tf2_msgs\srv\dds_opensplice\FrameGraph_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _FRAMEGRAPH_REQUEST_DCPS_H_
#define _FRAMEGRAPH_REQUEST_DCPS_H_

#include "sacpp_mapping.h"
#include "dds_dcps.h"
#include "FrameGraph_Request_.h"
#include "tf2_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace tf2_msgs
{
   namespace srv
   {
      namespace dds_
      {

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_TypeSupportInterface;

         typedef FrameGraph_Request_TypeSupportInterface * FrameGraph_Request_TypeSupportInterface_ptr;
         typedef DDS_DCPSInterface_var < FrameGraph_Request_TypeSupportInterface> FrameGraph_Request_TypeSupportInterface_var;
         typedef DDS_DCPSInterface_out < FrameGraph_Request_TypeSupportInterface> FrameGraph_Request_TypeSupportInterface_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_DataWriter;

         typedef FrameGraph_Request_DataWriter * FrameGraph_Request_DataWriter_ptr;
         typedef DDS_DCPSInterface_var < FrameGraph_Request_DataWriter> FrameGraph_Request_DataWriter_var;
         typedef DDS_DCPSInterface_out < FrameGraph_Request_DataWriter> FrameGraph_Request_DataWriter_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_DataReader;

         typedef FrameGraph_Request_DataReader * FrameGraph_Request_DataReader_ptr;
         typedef DDS_DCPSInterface_var < FrameGraph_Request_DataReader> FrameGraph_Request_DataReader_var;
         typedef DDS_DCPSInterface_out < FrameGraph_Request_DataReader> FrameGraph_Request_DataReader_out;


         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_DataReaderView;

         typedef FrameGraph_Request_DataReaderView * FrameGraph_Request_DataReaderView_ptr;
         typedef DDS_DCPSInterface_var < FrameGraph_Request_DataReaderView> FrameGraph_Request_DataReaderView_var;
         typedef DDS_DCPSInterface_out < FrameGraph_Request_DataReaderView> FrameGraph_Request_DataReaderView_out;

         struct FrameGraph_Request_Seq_uniq_ {};
         typedef DDS_DCPSUFLSeq < FrameGraph_Request_, struct FrameGraph_Request_Seq_uniq_> FrameGraph_Request_Seq;
         typedef DDS_DCPSSequence_var < FrameGraph_Request_Seq> FrameGraph_Request_Seq_var;
         typedef DDS_DCPSSequence_out < FrameGraph_Request_Seq> FrameGraph_Request_Seq_out;
         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_TypeSupportInterface
         :
            virtual public DDS::TypeSupport
         { 
         public:
            typedef FrameGraph_Request_TypeSupportInterface_ptr _ptr_type;
            typedef FrameGraph_Request_TypeSupportInterface_var _var_type;

            static FrameGraph_Request_TypeSupportInterface_ptr _duplicate (FrameGraph_Request_TypeSupportInterface_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static FrameGraph_Request_TypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
            static FrameGraph_Request_TypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static FrameGraph_Request_TypeSupportInterface_ptr _nil () { return 0; }
            static const char * _local_id;
            FrameGraph_Request_TypeSupportInterface_ptr _this () { return this; }


         protected:
            FrameGraph_Request_TypeSupportInterface () {};
            ~FrameGraph_Request_TypeSupportInterface () {};
         private:
            FrameGraph_Request_TypeSupportInterface (const FrameGraph_Request_TypeSupportInterface &);
            FrameGraph_Request_TypeSupportInterface & operator = (const FrameGraph_Request_TypeSupportInterface &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_DataWriter
         :
            virtual public DDS::DataWriter
         { 
         public:
            typedef FrameGraph_Request_DataWriter_ptr _ptr_type;
            typedef FrameGraph_Request_DataWriter_var _var_type;

            static FrameGraph_Request_DataWriter_ptr _duplicate (FrameGraph_Request_DataWriter_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static FrameGraph_Request_DataWriter_ptr _narrow (DDS::Object_ptr obj);
            static FrameGraph_Request_DataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static FrameGraph_Request_DataWriter_ptr _nil () { return 0; }
            static const char * _local_id;
            FrameGraph_Request_DataWriter_ptr _this () { return this; }

            virtual DDS::LongLong register_instance (const FrameGraph_Request_& instance_data) = 0;
            virtual DDS::LongLong register_instance_w_timestamp (const FrameGraph_Request_& instance_data, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long unregister_instance (const FrameGraph_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long unregister_instance_w_timestamp (const FrameGraph_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long write (const FrameGraph_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long write_w_timestamp (const FrameGraph_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long dispose (const FrameGraph_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long dispose_w_timestamp (const FrameGraph_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long writedispose (const FrameGraph_Request_& instance_data, DDS::LongLong handle) = 0;
            virtual DDS::Long writedispose_w_timestamp (const FrameGraph_Request_& instance_data, DDS::LongLong handle, const DDS::Time_t& source_timestamp) = 0;
            virtual DDS::Long get_key_value (FrameGraph_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const FrameGraph_Request_& instance_data) = 0;

         protected:
            FrameGraph_Request_DataWriter () {};
            ~FrameGraph_Request_DataWriter () {};
         private:
            FrameGraph_Request_DataWriter (const FrameGraph_Request_DataWriter &);
            FrameGraph_Request_DataWriter & operator = (const FrameGraph_Request_DataWriter &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_DataReader
         :
            virtual public DDS::DataReader
         { 
         public:
            typedef FrameGraph_Request_DataReader_ptr _ptr_type;
            typedef FrameGraph_Request_DataReader_var _var_type;

            static FrameGraph_Request_DataReader_ptr _duplicate (FrameGraph_Request_DataReader_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static FrameGraph_Request_DataReader_ptr _narrow (DDS::Object_ptr obj);
            static FrameGraph_Request_DataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static FrameGraph_Request_DataReader_ptr _nil () { return 0; }
            static const char * _local_id;
            FrameGraph_Request_DataReader_ptr _this () { return this; }

            virtual DDS::Long read (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (FrameGraph_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (FrameGraph_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (FrameGraph_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const FrameGraph_Request_& instance) = 0;

         protected:
            FrameGraph_Request_DataReader () {};
            ~FrameGraph_Request_DataReader () {};
         private:
            FrameGraph_Request_DataReader (const FrameGraph_Request_DataReader &);
            FrameGraph_Request_DataReader & operator = (const FrameGraph_Request_DataReader &);
         };

         class ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_tf2_msgs FrameGraph_Request_DataReaderView
         :
            virtual public DDS::DataReaderView
         { 
         public:
            typedef FrameGraph_Request_DataReaderView_ptr _ptr_type;
            typedef FrameGraph_Request_DataReaderView_var _var_type;

            static FrameGraph_Request_DataReaderView_ptr _duplicate (FrameGraph_Request_DataReaderView_ptr obj);
            DDS::Boolean _local_is_a (const char * id);

            static FrameGraph_Request_DataReaderView_ptr _narrow (DDS::Object_ptr obj);
            static FrameGraph_Request_DataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
            static FrameGraph_Request_DataReaderView_ptr _nil () { return 0; }
            static const char * _local_id;
            FrameGraph_Request_DataReaderView_ptr _this () { return this; }

            virtual DDS::Long read (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_w_condition (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_w_condition (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long read_next_sample (FrameGraph_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long take_next_sample (FrameGraph_Request_& received_data, DDS::SampleInfo& sample_info) = 0;
            virtual DDS::Long read_instance (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_instance (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long take_next_instance (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ULong sample_states, DDS::ULong view_states, DDS::ULong instance_states) = 0;
            virtual DDS::Long read_next_instance_w_condition (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long take_next_instance_w_condition (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::LongLong a_handle, DDS::ReadCondition_ptr a_condition) = 0;
            virtual DDS::Long return_loan (FrameGraph_Request_Seq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
            virtual DDS::Long get_key_value (FrameGraph_Request_& key_holder, DDS::LongLong handle) = 0;
            virtual DDS::LongLong lookup_instance (const FrameGraph_Request_& instance) = 0;

         protected:
            FrameGraph_Request_DataReaderView () {};
            ~FrameGraph_Request_DataReaderView () {};
         private:
            FrameGraph_Request_DataReaderView (const FrameGraph_Request_DataReaderView &);
            FrameGraph_Request_DataReaderView & operator = (const FrameGraph_Request_DataReaderView &);
         };

      }
   }
}




#endif
