//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: SetCameraInfo_Request_.h
//  Source: sensor_msgs\srv\dds_opensplice\SetCameraInfo_Request_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SETCAMERAINFO_REQUEST__H_
#define _SETCAMERAINFO_REQUEST__H_

#include "sacpp_mapping.h"
#include "CameraInfo_.h"
#include "sensor_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace sensor_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct SetCameraInfo_Request_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_sensor_msgs SetCameraInfo_Request_
         {
               ::sensor_msgs::msg::dds_::CameraInfo_ camera_info_;
         };

         typedef DDS_DCPSStruct_var < SetCameraInfo_Request_> SetCameraInfo_Request__var;
         typedef DDS_DCPSStruct_out < SetCameraInfo_Request_> SetCameraInfo_Request__out;
      }
   }
}




#endif
