//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetParameters_Response_.h
//  Source: rcl_interfaces\srv\dds_opensplice\GetParameters_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETPARAMETERS_RESPONSE__H_
#define _GETPARAMETERS_RESPONSE__H_

#include "sacpp_mapping.h"
#include "ParameterValue_.h"
#include "rcl_interfaces/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {
         struct GetParameters_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_rcl_interfaces GetParameters_Response_
         {
               struct _values__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < ::rcl_interfaces::msg::dds_::ParameterValue_, struct _values__seq_uniq_> _values__seq;
               typedef DDS_DCPSSequence_var < _values__seq> _values__seq_var;
               typedef DDS_DCPSSequence_out < _values__seq> _values__seq_out;
               _values__seq values_;
         };

         typedef DDS_DCPSStruct_var < GetParameters_Response_> GetParameters_Response__var;
         typedef DDS_DCPSStruct_out < GetParameters_Response_> GetParameters_Response__out;
      }
   }
}




#endif
