//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GetParameterTypes_Response_.h
//  Source: rcl_interfaces\srv\dds_opensplice\GetParameterTypes_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GETPARAMETERTYPES_RESPONSE__H_
#define _GETPARAMETERTYPES_RESPONSE__H_

#include "sacpp_mapping.h"
#include "rcl_interfaces/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {
         struct GetParameterTypes_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_rcl_interfaces GetParameterTypes_Response_
         {
               struct _types__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::Octet, struct _types__seq_uniq_> _types__seq;
               typedef DDS_DCPSSequence_var < _types__seq> _types__seq_var;
               typedef DDS_DCPSSequence_out < _types__seq> _types__seq_out;
               _types__seq types_;
         };

         typedef DDS_DCPSStruct_var < GetParameterTypes_Response_> GetParameterTypes_Response__var;
         typedef DDS_DCPSStruct_out < GetParameterTypes_Response_> GetParameterTypes_Response__out;
      }
   }
}




#endif
