//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_GetParameters_Response_.h
//  Source: rcl_interfaces\srv\dds_opensplice\Sample_GetParameters_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SAMPLE_GETPARAMETERS_RESPONSE__H_
#define _SAMPLE_GETPARAMETERS_RESPONSE__H_

#include "sacpp_mapping.h"
#include "GetParameters_Response_.h"
#include "rcl_interfaces/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace rcl_interfaces
{
   namespace srv
   {
      namespace dds_
      {
         struct Sample_GetParameters_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_rcl_interfaces Sample_GetParameters_Response_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               GetParameters_Response_ response_;
         };

         typedef DDS_DCPSStruct_var < Sample_GetParameters_Response_> Sample_GetParameters_Response__var;
         typedef DDS_DCPSStruct_out < Sample_GetParameters_Response_> Sample_GetParameters_Response__out;
      }
   }
}




#endif
