//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_AddDiagnostics_Response_.h
//  Source: diagnostic_msgs\srv\dds_opensplice\Sample_AddDiagnostics_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SAMPLE_ADDDIAGNOSTICS_RESPONSE__H_
#define _SAMPLE_ADDDIAGNOSTICS_RESPONSE__H_

#include "sacpp_mapping.h"
#include "AddDiagnostics_Response_.h"
#include "diagnostic_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace diagnostic_msgs
{
   namespace srv
   {
      namespace dds_
      {
         struct Sample_AddDiagnostics_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_diagnostic_msgs Sample_AddDiagnostics_Response_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               AddDiagnostics_Response_ response_;
         };

         typedef DDS_DCPSStruct_var < Sample_AddDiagnostics_Response_> Sample_AddDiagnostics_Response__var;
         typedef DDS_DCPSStruct_out < Sample_AddDiagnostics_Response_> Sample_AddDiagnostics_Response__out;
      }
   }
}




#endif
