//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: GridCells_.h
//  Source: nav_msgs\msg\dds_opensplice\GridCells_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _GRIDCELLS__H_
#define _GRIDCELLS__H_

#include "sacpp_mapping.h"
#include "Point_.h"
#include "Header_.h"
#include "nav_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace nav_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct GridCells_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_nav_msgs GridCells_
         {
               struct _cells__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < ::geometry_msgs::msg::dds_::Point_, struct _cells__seq_uniq_> _cells__seq;
               typedef DDS_DCPSSequence_var < _cells__seq> _cells__seq_var;
               typedef DDS_DCPSSequence_out < _cells__seq> _cells__seq_out;
               ::std_msgs::msg::dds_::Header_ header_;
               DDS::Float cell_width_;
               DDS::Float cell_height_;
               _cells__seq cells_;
         };

         typedef DDS_DCPSStruct_var < GridCells_> GridCells__var;
         typedef DDS_DCPSStruct_out < GridCells_> GridCells__out;
      }
   }
}




#endif
