//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Sample_ConfigLogger_Response_.h
//  Source: logging_demo\srv\dds_opensplice\Sample_ConfigLogger_Response_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _SAMPLE_CONFIGLOGGER_RESPONSE__H_
#define _SAMPLE_CONFIGLOGGER_RESPONSE__H_

#include "sacpp_mapping.h"
#include "ConfigLogger_Response_.h"
#include "logging_demo/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace logging_demo
{
   namespace srv
   {
      namespace dds_
      {
         struct Sample_ConfigLogger_Response_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_logging_demo Sample_ConfigLogger_Response_
         {
               DDS::ULongLong client_guid_0_;
               DDS::ULongLong client_guid_1_;
               DDS::LongLong sequence_number_;
               ConfigLogger_Response_ response_;
         };

         typedef DDS_DCPSStruct_var < Sample_ConfigLogger_Response_> Sample_ConfigLogger_Response__var;
         typedef Sample_ConfigLogger_Response_&Sample_ConfigLogger_Response__out;
      }
   }
}




#endif
