//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: CompressedImage_.h
//  Source: sensor_msgs\msg\dds_opensplice\CompressedImage_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _COMPRESSEDIMAGE__H_
#define _COMPRESSEDIMAGE__H_

#include "sacpp_mapping.h"
#include "Header_.h"
#include "sensor_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace sensor_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct CompressedImage_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_sensor_msgs CompressedImage_
         {
               struct _data__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::Octet, struct _data__seq_uniq_> _data__seq;
               typedef DDS_DCPSSequence_var < _data__seq> _data__seq_var;
               typedef DDS_DCPSSequence_out < _data__seq> _data__seq_out;
               ::std_msgs::msg::dds_::Header_ header_;
               DDS::String_mgr format_;
               _data__seq data_;
         };

         typedef DDS_DCPSStruct_var < CompressedImage_> CompressedImage__var;
         typedef DDS_DCPSStruct_out < CompressedImage_> CompressedImage__out;
      }
   }
}




#endif
