//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Joy_.h
//  Source: sensor_msgs\msg\dds_opensplice\Joy_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _JOY__H_
#define _JOY__H_

#include "sacpp_mapping.h"
#include "Header_.h"
#include "sensor_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace sensor_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Joy_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_sensor_msgs Joy_
         {
               struct _axes__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::Float, struct _axes__seq_uniq_> _axes__seq;
               typedef DDS_DCPSSequence_var < _axes__seq> _axes__seq_var;
               typedef DDS_DCPSSequence_out < _axes__seq> _axes__seq_out;
               struct _buttons__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < DDS::Long, struct _buttons__seq_uniq_> _buttons__seq;
               typedef DDS_DCPSSequence_var < _buttons__seq> _buttons__seq_var;
               typedef DDS_DCPSSequence_out < _buttons__seq> _buttons__seq_out;
               ::std_msgs::msg::dds_::Header_ header_;
               _axes__seq axes_;
               _buttons__seq buttons_;
         };

         typedef DDS_DCPSStruct_var < Joy_> Joy__var;
         typedef DDS_DCPSStruct_out < Joy_> Joy__out;
      }
   }
}




#endif
