//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: PointCloud_.h
//  Source: sensor_msgs\msg\dds_opensplice\PointCloud_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _POINTCLOUD__H_
#define _POINTCLOUD__H_

#include "sacpp_mapping.h"
#include "Point32_.h"
#include "Header_.h"
#include "ChannelFloat32_.h"
#include "sensor_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace sensor_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct PointCloud_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_sensor_msgs PointCloud_
         {
               struct _points__seq_uniq_ {};
               typedef DDS_DCPSUFLSeq < ::geometry_msgs::msg::dds_::Point32_, struct _points__seq_uniq_> _points__seq;
               typedef DDS_DCPSSequence_var < _points__seq> _points__seq_var;
               typedef DDS_DCPSSequence_out < _points__seq> _points__seq_out;
               struct _channels__seq_uniq_ {};
               typedef DDS_DCPSUVLSeq < ChannelFloat32_, struct _channels__seq_uniq_> _channels__seq;
               typedef DDS_DCPSSequence_var < _channels__seq> _channels__seq_var;
               typedef DDS_DCPSSequence_out < _channels__seq> _channels__seq_out;
               ::std_msgs::msg::dds_::Header_ header_;
               _points__seq points_;
               _channels__seq channels_;
         };

         typedef DDS_DCPSStruct_var < PointCloud_> PointCloud__var;
         typedef DDS_DCPSStruct_out < PointCloud_> PointCloud__out;
      }
   }
}




#endif
