//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Range_.h
//  Source: sensor_msgs\msg\dds_opensplice\Range_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _RANGE__H_
#define _RANGE__H_

#include "sacpp_mapping.h"
#include "Header_.h"
#include "sensor_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace sensor_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct Range_;
         const DDS::Octet Range__ULTRASOUND = (DDS::Octet) 0;
         const DDS::Octet Range__INFRARED = (DDS::Octet) 1;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_sensor_msgs Range_
         {
               ::std_msgs::msg::dds_::Header_ header_;
               DDS::Octet radiation_type_;
               DDS::Float field_of_view_;
               DDS::Float min_range_;
               DDS::Float max_range_;
               DDS::Float range_;
         };

         typedef DDS_DCPSStruct_var < Range_> Range__var;
         typedef DDS_DCPSStruct_out < Range_> Range__out;
      }
   }
}




#endif
