//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: RegionOfInterest_.h
//  Source: sensor_msgs\msg\dds_opensplice\RegionOfInterest_.idl
//  Generated: timestamp removed to make the build reproducible
//  OpenSplice 6.7.180404OSS
//  
//******************************************************************
#ifndef _REGIONOFINTEREST__H_
#define _REGIONOFINTEREST__H_

#include "sacpp_mapping.h"
#include "sensor_msgs/msg/rosidl_typesupport_opensplice_cpp__visibility_control.h"


namespace sensor_msgs
{
   namespace msg
   {
      namespace dds_
      {
         struct RegionOfInterest_;

         struct ROSIDL_TYPESUPPORT_OPENSPLICE_CPP_PUBLIC_sensor_msgs RegionOfInterest_
         {
               DDS::ULong x_offset_;
               DDS::ULong y_offset_;
               DDS::ULong height_;
               DDS::ULong width_;
               DDS::Boolean do_rectify_;
         };

         typedef DDS_DCPSStruct_var < RegionOfInterest_> RegionOfInterest__var;
         typedef RegionOfInterest_&RegionOfInterest__out;
      }
   }
}




#endif
